### ISSUE TITLE
Change colors from hex to hsl

### ISSUE THREAD

**Issue by KonradLinkowski** [KonradLinkowski/Population#9]
Storing the colors as `[int, int, int]` tuple and converting it to valid `fillStyle` with
```
const getHSL (h, s, l) => `hsl(${h}, ${s}%, ${l}%)`
```
would be much more efficient and human-readable.

**Comment by mvpmaddy** [comment]
@KonradLinkowski Can I work on this issue.
I'm a first timer.

**Comment by Sacules** [comment]
Hi, I'd like to tackle this :)
